export const GET_POPULATION = 'GET_POPULATION';
export const GET_COUNTIES = 'GET_COUNTIES';
export const GET_BIRTHS = 'GET_BIRTHS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const GET_COUNTY_NAMES = 'GET_COUNTY_NAMES';
